version: '3'
services:
  server:
    image: atlasiro/my-test-app:latest_v54
    ports:
      - "8080:8080"
    extra_hosts:
    - "host.docker.internal:host-gateway"
    container_name: simple
    depends_on:
      - db
  db:
    image: postgres:latest  
    environment:
      POSTGRES_USER: rhogoron
      POSTGRES_PASSWORD: rhogoron
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  nginx:
      image: nginx
      ports:
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d
      depends_on:
        - server